version: '3.1'

services:
  db:
    image: postgres
    container_name: 'pynea-postgres'
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: pynea